### ISSUE TITLE
More of a question, to be honest.

### ISSUE THREAD

**Issue by unkownpit** [PinkSwitch/Live-A-Live-Internal-Randomizer#1]
how does one go about the randomizer settings? when I press the X button in the randomizer menu, and I type in a seed, it just sets me back to seed 000000. is there something else I have to do? pressing a, b and y, dont do it, and my L button is broken (CFW) (I have no way of emulating this in another way.) also, it seems that 2010 snes9x does not run this, while the one from 2019 does. I have to use blarg snes for this.

**Comment by WickBRSTM** [comment]
There seems to be some issues with older versions of Snes9x based on what I'm seeing in the Discord. I've had no problem running a random seed in BSNES v115 for what it's worth, but I'll play around with the settings a bit to see if I can answer your question

**Comment by PinkSwitch** [comment]
Hi! Somehow I missed this. Unfortunately, this is an emulation an error.  Some older emulators cannot properly process the randomizer's data, such as the seed number, or skills and such. However, I did, I believe, fix the crash that would occur on some emulators on the title screen. You might want to try the 2010 snes9x now that 2.0 has patched out some of the incompatibility. I can't gurantee it will work perfectly, though.
